### ISSUE TITLE
Warn for currencies where minimum unit is not ammount/100

### ISSUE THREAD

**Issue by maswan** [neicnordic/indico-plugin-stripe#10]
If the currency is JPY or any other zero-decimal currencies, we should not divide by 100. See https://stripe.com/docs/currencies#presentment-currencies for reference of which are.

Quick fix to refuse to work if of those currencies set would probably be fine as an interim solution.

**Comment by bow** [comment]
All right, with 78286f0 the plugin should now handle these zero decimal currencies better. Not too happy that we have to hard code these currencies in `utils.py`, but I couldn't find a way to query these currencies from the API itself, so these are hard coded in the plugin. This is also suggested in a mail thread by Stripe's rep [here](https://groups.google.com/a/lists.stripe.com/forum/#!topic/api-discuss/IsiAW3uEfHQ)).

Anyway, I've also updated the tests with one of the zero decimal currencies. I'll close this for now, feel free to reopen if needed.
