### ISSUE TITLE
Show Stripe receipt after a successful checkout

### ISSUE THREAD

**Issue by bow** [neicnordic/indico-plugin-stripe#6]
Since Stripe seems to provide a URL for given checkout, it seems useful to also show this on the successful checkout page.

**Comment by amgadhanafy** [comment]
related issue 
https://github.com/indico/indico/issues/751

**Comment by bow** [comment]
We got it working now in 95e1b1e5a03c49b777de36550f4155f253d45e2f. The URL is shown as a link in the flashed message.
